 
name: OctoBot Notification
on:
  pull_request:
    branches:
      - master
jobs:
  pull_request_notification:
    runs-on: ubuntu-latest
    steps:
      - name: PR Opened
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          username: OctoBot
          avatarUrl: https://res.cloudinary.com/bruncky/image/upload/v1583702627/Main/Octocat_k3esra.png
          description: "**Event:** ${{ github.EVENT_NAME }}\n**Repo:** ${{ github.REPOSITORY }}\n**Author:** ${{ github.ACTOR }}\n**Title:** ${{ event }}\n**Body:** ${{ event }}\n**Branch:** ${{ github.HEAD_REF }}"
          severity: info
          color: '#ff00aa'
          webhookUrl: ${{ secrets.OCTO_BOT }}
